                                                                                                                                                                                  







# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    begin
      xcode_select("/Applications/Xcode_15.0.app")
      build_number = Time.new.strftime("%Y%m%d%H%M%S")
      increment_build_number(build_number: build_number,xcodeproj: "E Commerce.xcodeproj")
      
      update_project_team(
          path: "E Commerce.xcodeproj",
          teamid: "M6ENXWGY3Q"
      )
      
      build_number = Time.new.strftime("%Y%m%d%H%M%S")
      increment_build_number(build_number: build_number,xcodeproj: "E Commerce.xcodeproj")
      build_app( 
        scheme: "E Commerce", 
        output_name: "E Commerce.ipa",
        export_options: {
            method: "ad-hoc"
          }
      )
      app_pool = sh("curl -F 'file=@/Users/cicd/jnode/workspace/E-Commerce/E Commerce/E Commerce.ipa' -X POST -k https://apps.teamta.net/uploadbinary.php")
      inter_ =app_pool.to_s
      sh("touch curl_slack.log")
      sh("echo '#{inter_}' >> curl_slack.log")
      real_link = sh("tail -1 curl_slack.log")
      trimStr = (real_link.to_s).lstrip
      trimedStringLink = ("(#{trimStr})").delete("\n")
      gitMsg    = sh("git log -1 --pretty=%B")
    end
  end
  end




















